### ISSUE TITLE
High CPU Utilization when running meteor with "npm start"

### ISSUE THREAD

**Issue by mr-rob0to** [MeteorKits/starter-kit-react#1]
CPU spikes over 100% when running with `npm start` as opposed to just `meteor run` or just `meteor`.  This happens after running the app for a bit.

**OS: OS X (10.11.4)**
**NPM version : 3.8.3**
**Node version: v4.3.1**

**Comment by floydprice** [comment]
Thanks for the feedback, i have not noticed this but as the solution is to just run the meteor CLI directly I wont spend any time investigating and have updated the README.MD.
